spring.application.name=carteiraDeinvestimentos-service

server.port=3000

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.sql.init.mode=always

# Configuracao do banco de dados

spring.datasource.url=jdbc:postgresql://localhost:5432/carteiraInvestimentos
spring.datasource.username=postgres
spring.datasource.password=19160326JhG#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


brapi.api.token=3RvdzhyJWTUyiMXK6rpQSX